import type { Metadata } from "next";
import { Geist, Geist_Mono, Literata, Work_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const literata = Literata({
  subsets: ["latin-ext"],
  variable: "--font-literata",
  display: "swap",
});

const workSans = Work_Sans({
  subsets: ["latin-ext"],
  variable: "--font-worksans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${literata.variable} ${literata.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
