import type { Metadata } from "next";
import { Literata } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const literata = Literata({
  subsets: ["latin-ext"],
  variable: "--font-literata",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${literata.variable} ${literata.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
